# Generated by Django 3.2.15 on 2022-08-22 08:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=32)),
                ('vehicle_registration_id', models.CharField(editable=False, max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=200, editable=False, max_digits=10)),
                ('discount', models.IntegerField(blank=True, default=20, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('starting_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
